// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });
import styles from '../styles/home.module.scss';
import Heading from "@/components/Heading";
import Socials from "@/components/Socials";
import axios from "axios";
import { GetStaticProps } from "next";
import Head from "next/head";
import { FC } from "react";


export const getStaticProps:GetStaticProps = async () => {
	const { data } = await axios(`${process.env.API_HOST}/socials/`);
	if(!data) { return { notFound: true} }
	return {props: {socials: data}}
}

type Props = {
	socials: socialsType[]
}

const Home:FC<Props> = ({socials}) => {

  return (
    <>
      <Head>
        <title>My Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>
        <Heading text="NEXT.js"/>
        <Socials socials={socials} />
      </div>
    </>
  );
  
}


export default Home;